{
 "title": "Apex Central",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Apex Central", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Evénements récents",
   "type": "stat",
   "description": "Nombre d'événement enregistrés des dernières 24h.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_total_event{nombre_event=\"1j\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre d'événements",
   "type": "timeseries",
   "description": "Timeline du nombre d'événements des dernières 24 heures.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "apex_total_event{job=\"apex\", nombre_event=\"1j\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Détails des événements",
   "type": "table",
   "description": "Détails des événements des dernières 24 heures. Triés par Dossier, Utilisateur et Date.",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "apex_priority_event", "legendFormat": "__auto" }
   ]
  }
 ]
}